import { spawn } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";

/** Optional figure backends: Mermaid (diagrams) and Python/matplotlib (data
 * plots). Both are fallback-first: their deterministic source files are always
 * written. Full release mode declares the matplotlib plot in the publication
 * manifest and preflight requires it; lite uses the local pgfplots fallback.
 * Nano Banana-style generative visuals remain budget-gated model work. */

export type FigureBackendId = "mermaid" | "python";

export type BackendStatus = {
  backend: FigureBackendId;
  available: boolean;
  detail: string;
  rendered: string[];
};

const RENDER_TIMEOUT_MS = 60_000;

function run(bin: string, args: string[], cwd: string, timeoutMs: number): Promise<{ code: number | null; output: string }> {
  return new Promise((resolve) => {
    const child = spawn(bin, args, { cwd, stdio: ["ignore", "pipe", "pipe"] });
    const chunks: Buffer[] = [];
    const timer = setTimeout(() => child.kill("SIGTERM"), timeoutMs);
    child.stdout.on("data", (c: Buffer) => chunks.push(c));
    child.stderr.on("data", (c: Buffer) => chunks.push(c));
    child.on("error", (err) => {
      clearTimeout(timer);
      resolve({ code: null, output: String(err) });
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      resolve({ code, output: Buffer.concat(chunks).toString("utf-8") });
    });
  });
}

export function mermaidBin(): string {
  return process.env.LONGWRITE_MMDC_BIN?.trim() || "mmdc";
}

export function pythonBin(): string {
  return process.env.LONGWRITE_PYTHON_BIN?.trim() || "python3";
}

export async function detectMermaid(): Promise<boolean> {
  return (await run(mermaidBin(), ["--version"], process.cwd(), 10_000)).code === 0;
}

/** Render a specific Mermaid contract for publication placement. The caller
 * keeps a deterministic TikZ/SVG fallback, so Mermaid remains an enhancement
 * rather than a hidden hard dependency. */
export async function renderMermaidFile(workspaceDir: string, input: string, output: string): Promise<boolean> {
  if (!(await detectMermaid())) return false;
  return (await run(mermaidBin(), ["-i", input, "-o", output, "--quiet"], workspaceDir, RENDER_TIMEOUT_MS)).code === 0;
}

export async function cropPdfFile(workspaceDir: string, input: string, output: string): Promise<boolean> {
  const bin = process.env.LONGWRITE_PDFCROP_BIN?.trim() || "pdfcrop";
  return (await run(bin, [input, output], workspaceDir, RENDER_TIMEOUT_MS)).code === 0;
}

export async function detectPython(): Promise<boolean> {
  return (await run(pythonBin(), ["-c", "import matplotlib"], process.cwd(), 15_000)).code === 0;
}

/** Deterministic Mermaid source for the research pipeline diagram. */
export function researchPipelineMermaid(): string {
  return [
    "flowchart LR",
    "  intake[Project intake] --> recall[Literature recall]",
    "  recall --> score[Source scoring]",
    "  score --> classify[Classification]",
    "  classify --> outline[Outline]",
    "  outline --> draft[Draft sections]",
    "  draft --> loop",
    "  subgraph loop[Quality loop]",
    "    review[Peer review] --> route[Route weaknesses]",
    "    route --> revise[Revise]",
    "    revise --> rebuild[Rebuild]",
    "    rebuild --> review",
    "  end",
    "  loop --> build[Final manuscript]",
    "",
  ].join("\n");
}

/** Deterministic matplotlib script plotting sources-per-year from the CSV the
 *  deterministic figure step already emits. */
export function sourceYearsPlotScript(): string {
  return [
    "#!/usr/bin/env python3",
    '"""Generated by LongWrite: plot sources per publication year."""',
    "import csv",
    "import pathlib",
    "",
    "import matplotlib",
    'matplotlib.use("Agg")',
    "import matplotlib.pyplot as plt",
    "",
    'root = pathlib.Path(__file__).resolve().parent.parent',
    'rows = list(csv.DictReader((root / "data" / "source-years.csv").open()))',
    'years = [int(r["year"]) for r in rows]',
    'counts = [int(r["count"]) for r in rows]',
    'positions = list(range(len(years)))',
    'tick_step = max(1, (len(years) + 9) // 10)',
    'tick_positions = sorted(set(positions[::tick_step] + ([positions[-1]] if positions else [])))',
    "",
    "fig, ax = plt.subplots(figsize=(8, 4.5))",
    'ax.bar(positions, counts, color="#2563eb")',
    'ax.set_xticks(tick_positions, [str(years[i]) for i in tick_positions], rotation=45, ha="right")',
    'ax.tick_params(axis="x", labelsize=8)',
    'ax.set_title("Sources by publication year")',
    'ax.set_xlabel("Year")',
    'ax.set_ylabel("Sources")',
    "fig.tight_layout(pad=1.2)",
    'fig.savefig(root / "figures" / "source-years-plot.png", dpi=150)',
    "",
  ].join("\n");
}

export type FigureBackendResult = {
  written: string[];
  statuses: BackendStatus[];
};

export async function renderFigureBackends(workspaceDir: string): Promise<FigureBackendResult> {
  const written: string[] = [];
  const writeFile = async (rel: string, content: string) => {
    await fs.mkdir(path.dirname(path.join(workspaceDir, rel)), { recursive: true });
    await fs.writeFile(path.join(workspaceDir, rel), content, "utf-8");
    written.push(rel);
  };

  await writeFile("figures/workflow.mmd", researchPipelineMermaid());
  await writeFile("scripts/plot_source_years.py", sourceYearsPlotScript());

  const statuses: BackendStatus[] = [];

  const mermaid: BackendStatus = { backend: "mermaid", available: await detectMermaid(), detail: "", rendered: [] };
  if (mermaid.available) {
    const result = await run(
      mermaidBin(),
      ["-i", "figures/workflow.mmd", "-o", "figures/workflow.svg", "--quiet"],
      workspaceDir,
      RENDER_TIMEOUT_MS,
    );
    if (result.code === 0) {
      mermaid.rendered.push("figures/workflow.svg");
      written.push("figures/workflow.svg");
      mermaid.detail = "rendered figures/workflow.svg";
    } else {
      mermaid.detail = `mmdc failed: ${result.output.slice(0, 300)}`;
    }
  } else {
    mermaid.detail = "mmdc not found (npm i -g @mermaid-js/mermaid-cli, or set LONGWRITE_MMDC_BIN); source kept at figures/workflow.mmd";
  }
  statuses.push(mermaid);

  const python: BackendStatus = { backend: "python", available: await detectPython(), detail: "", rendered: [] };
  if (python.available) {
    const result = await run(pythonBin(), ["scripts/plot_source_years.py"], workspaceDir, RENDER_TIMEOUT_MS);
    if (result.code === 0) {
      python.rendered.push("figures/source-years-plot.png");
      written.push("figures/source-years-plot.png");
      python.detail = "rendered figures/source-years-plot.png";
    } else {
      python.detail = `plot script failed: ${result.output.slice(0, 300)}`;
    }
  } else {
    python.detail = "python3 with matplotlib not found (pip install matplotlib, or set LONGWRITE_PYTHON_BIN); script kept at scripts/plot_source_years.py";
  }
  statuses.push(python);

  const report = [
    "# Figure Backends Report",
    "",
    ...statuses.flatMap((status) => [
      `## ${status.backend}`,
      "",
      `- Available: ${status.available ? "yes" : "no"}`,
      `- ${status.detail}`,
      ...(status.rendered.length > 0 ? status.rendered.map((r) => `- Rendered: ${r}`) : []),
      "",
    ]),
  ].join("\n");
  await writeFile("reports/figures-build.md", report);

  return { written, statuses };
}
